### ISSUE TITLE
Release of 2.2.1 for Kinetic

### ISSUE THREAD

**Issue by MichaelT64** [xqms/rosmon#104]
Hi

Are there plans to release version 2.2.1 also for Kinetic?

Michael

**Comment by xqms** [comment]
My general plan was to let the Melodic community test things for a bit and then release to Kinetic.
Can you maybe help with system-level testing on Kinetic?

**Comment by xqms** [comment]
Finally got around to this (see #115). 2.2.1 is now released for Kinetic.
