### ISSUE TITLE
Add key binding to start/stop all nodes

### ISSUE THREAD

**Issue by rgreid** [xqms/rosmon#127]
Is there any interest in a PR to add two new key bindings?  One to start all nodes, and the other to stop?  Similar to the mute/unmute all [bindings here](https://github.com/xqms/rosmon/blob/master/rosmon_core/src/ui.cpp#L654).  

If there's interest in a PR, what should the bindings be? e.g. F7 and F8? 

Use case: We're running multiple`rosmon` instances inside `tmux` with `--no-start`, and frequently find ourselves mashing a-s, b-s, c-s, d-s... etc.

**Comment by xqms** [comment]
Of course, PRs are always welcome. Your use case is interesting, I never thought about doing it that way ;)
