### ISSUE TITLE
handle launch-prefix

### ISSUE THREAD

**Issue by lenzc** [xqms/rosmon#13]
rosmon did not detect missing valgrind installation

**Comment by xqms** [comment]
Fixed in ed2671305e962665b727275c0edd2255a18c67c7. I'm waiting for the ROS maintainers to accept the new release, maybe we'll still make it in time for the kinetic package sync....
https://github.com/ros/rosdistro/pull/17597

**Comment by xqms** [comment]
Released for Kinetic.
