### ISSUE TITLE
<include> attribute, `pass_all_args`  not recognized/supported

### ISSUE THREAD

**Issue by BrettHemes** [xqms/rosmon#14]
As the title suggests, using this on my projects I had issues with arguments not properly being passed through to subsequent launch files when using `<include>` with the `pass_all_args` attribute.

**Comment by xqms** [comment]
#15 contains an implementation of `pass_all_args` support - I'll test it on the more complex systems we have before merging it, though.

**Comment by BrettHemes** [comment]
Awesome, I can test this out this afternoon along with #17
