### ISSUE TITLE
terminal input

### ISSUE THREAD

**Issue by akashjinandra** [xqms/rosmon#142]
Hello, is it possible to accept cin input via terminal when running multiple nodes?

**Comment by xqms** [comment]
Hey, rosmon currently takes control of the keyboard, no application can get data via stdin (it doesn't matter if it is multiple nodes or a single one). I *could* imagine a feature where you select a node and request that you will be connected directly to the node - with some sort of escape key combination to get back to rosmon. But this is not something I need, so if you need it, please write a PR :)
But in my opinion, interactive nodes should be started outside of rosmon.

**Comment by akashjinandra** [comment]
Thanks for the input. I will look into this!
