### ISSUE TITLE
Wrong YAML whitespace parsing inside helper functions like deg()

### ISSUE THREAD

**Issue by peci1** [xqms/rosmon#163]
a.yaml

    a: deg(  0.1)

a.launch

    <launch>
      <rosparam command="load" file="$(dirname)/a.yaml" />
    </launch>

results in:

    $ mon launch /tmp/a.launch 
    Could not load launch file: /tmp/a.launch:2: error while parsing rosparam input file /tmp/a.yaml: /tmp/a.launch:2: Caught Python exception while evaluating rosparam expression '  0.1'):
    IndentationError: ('unexpected indent', ('<string>', 1, 2, '  0.1'))

Removing the whitespace inside `deg()` fixes the issue, but even with the whitespace it should be a valid YAML syntax (at least roslaunch digests it well).

**Comment by xqms** [comment]
Thanks for reporting! This should be fixed in master via #164 - if you still notice issues, please reopen the issue.
