### ISSUE TITLE
Restart a stopped node automatically

### ISSUE THREAD

**Issue by MichaelT64** [xqms/rosmon#31]
Hello
Is there a possibility to restart a node which is stopped by an error automatically? Or is this a feature request ;-) ?
Background: My Raspberry terminates serial communication to my hardware board from time to time (don't know why) and I have to restart the node by hand (which is very easy with rosmon). Having a parameter per node which automates that would make this even easier.
Michael

**Comment by xqms** [comment]
Hi, that's exactly what `respawn` is for (see https://wiki.ros.org/roslaunch/XML/node#Attributes). As long as your node exits with an abnormal exit code (!= 0), it will be automatically restarted (even with plain roslaunch). Does that help in your case?

**Comment by MichaelT64** [comment]
Hi
Restart with respawn="true" works fine, thanks for the pointer.
But after the following failure

> bridge: [run]: Protocol version of client is unrecognized, expected Rev 1 (rosserial 0.5+)
> bridge: [run]: wrong checksum for topic id and msg
> bridge: Traceback (most recent call last):
> bridge:   File "/opt/husarion/tools/rpi-linux/ros-core2-client", line 89, in <module>
> bridge:     client.run()
> bridge:   File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosserial_python/SerialClient.py", line 504, in run
> bridge:     self.callbacks[topic_id](msg)
> bridge:   File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosserial_python/SerialClient.py", line 107, in handlePacket
> bridge:     m.deserialize(data)
> bridge:   File "/opt/ros/kinetic/lib/python2.7/dist-packages/sensor_msgs/msg/_BatteryState.py", line 264, in deserialize
> bridge:     raise genpy.DeserializationError(e) #most likely buffer underfill
> bridge: genpy.message.DeserializationError: unpack requires a string argument of length 4
> bridge: bridge exited with status 1

no automatically restart happens without the respawn attribute.

Michael

**Comment by xqms** [comment]
Could you share your launch file, please? If the node really exits with nonzero exit status and `respawn` does not restart the node, this is a bug that needs to be fixed.

**Comment by MichaelT64** [comment]
My launch file is as follows:

```
<launch>
      <node pkg="serial_bridge" type="bridge.sh" name="bridge" output="screen" respawn="true" />
</launch>
```

and my bash file:

```
#!/bin/bash
/opt/husarion/tools/rpi-linux/ros-core2-client /dev/serial0
```
But the respawn does work, the restart in case of error without respawn does not work.

**Comment by xqms** [comment]
> But the respawn does work, the restart in case of error without respawn does not work.

I'm not sure if I understand you correctly. Just to be clear: With `respawn=true`, your node is restarted correctly in every case? You just want it to happen without `respawn=true`?

In that case: `rosmon` can not restart crashed nodes by default, since they might perform unintended/dangerous actions if restarted. That is why you have to enable this logic using `respawn=true`.

**Comment by MichaelT64** [comment]
Ah, than I missunderstand you. So as you described in your previous post everything is ok!
With respawn="true" the node was restarted, without respawn="true" not.
Thanks again.
