### ISSUE TITLE
is there any way for not stoping node and get log data

### ISSUE THREAD

**Issue by sunil1349** [xqms/rosmon#67]
here we are closing node and opening new one and getting log data , i do not want to close in want only log messages into file or i will publish that msg by my own. Is there anything like that

**Comment by xqms** [comment]
Sorry, I don't understand your message. Can you try to explain more?

Maybe you are looking for this feature: #36 ?

**Comment by sunil1349** [comment]
hi
in rosmon we are getting log messages into terminal , i want log messages
into tcp server without disturbing remaining nodes like with shutingdown
nodes is it possibile

**Comment by xqms** [comment]
>  i want log messages into tcp server
What tcp server?

Maybe you are looking for the ROS log topic? (try `rostopic echo /rosout_agg` or the rqt log viewer plugin)

**Comment by sunil1349** [comment]
i want log messages into my own gui application or my own file

**Comment by xqms** [comment]
Okay, then just subscribe to the `/rosout_agg` topic in your application - that captures everything that is logged using the `rosconsole` logging system.

I'm closing this, since it is already available outside of `rosmon`.
