### ISSUE TITLE
Missing namespace in NodeState message

### ISSUE THREAD

**Issue by arturmiller** [xqms/rosmon#77]
Hello,

I really like this project. However I have the issue, that the NodeState message does not contain the namespace. In my project I have nodes with the same name, which are only distinguishable by the namespace.
I don’t know if I’m missing something or if this is simply a missing feature. If you want I could create a PR.

**Comment by xqms** [comment]
You're right - that feature is certainly missing. If you want to contribute, I'd welcome a PR :+1:

We should probably display the namespace in `rqt_rosmon` as well. Maybe making the node list hierarchical would be possible... But let's start small and modify the messages first.
