### ISSUE TITLE
rosparam with inline yaml and argument substitution not working

### ISSUE THREAD

**Issue by matawed** [xqms/rosmon#83]
#### problem
mon launch reports ` Substitution error: $(arg traffic_topic_name_generic       ): Unknown arg`

#### input
for the following launch file:

```
<launch>
    <!--****************************************
    **********   Program Parameters   **********
    *****************************************-->

    <arg name="traffic_topic_name_generic" default="example_name"/>


    <!--*********************************
    **********   Launch Node   **********
    **********************************-->
        <node pkg="package" type="type" name="name" output="screen" >
            <rosparam param="topic_names" subst_value="true" command="load">
                traffic_topic_name_generic:        $(arg traffic_topic_name_generic       )
            </rosparam>
        </node>
</launch>
```

#### workaround
It seems that the trailing whitespaces after the arg name cause the problem, since the following line works
`traffic_topic_name_generic:        $(arg traffic_topic_name_generic)`

#### rosmon version
2.0.2 ubuntu 18.04. ros melodic

**Comment by xqms** [comment]
Thanks for the report, I'll look into it. I guess this is one of the cases were `roslaunch` is more lenient than the spec, so we'll have to adapt.
