### ISSUE TITLE
Unsafe operations after fork() in node_monitor.cpp

### ISSUE THREAD

**Issue by mikexing2018** [xqms/rosmon#88]
In the fork() documentation (http://man7.org/linux/man-pages/man2/fork.2.html), it states that:

"After a fork() in a multithreaded program, the child can safely
          call only async-signal-safe functions (see signal-safety(7)) until
          such time as it calls execve(2)."

In node_monitor.cpp, we are using setenv, strdup and other operations that are unsafe since they all internally using malloc(). There could be rare cases memory corruption issues.

More reference to this issue: https://www.linuxprogrammingblog.com/threads-and-fork-think-twice-before-using-them

**Comment by xqms** [comment]
Ah, I wasn't aware of this problem. Thanks for reporting!

The threads I'm using inside `LaunchConfig` have exited at that point, but roscpp uses threads internally - and I can't stop them prior to forking. I think the reason that there was no problem so far is that these ROS threads are all sleeping at that point (which is of course pure luck).

A solution could be to build a small "shim" executable that performs the needed operations and then `execve()s` the real target executable. Then we could really perform the `execve` immediately after `fork` inside rosmon. I'll investigate that.
